---
title: "DCM Assessment Report"
format:
  typst:
    toc-title: Contents
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
---

```{python}
#| tags: [parameters]

threshold = .8
```

```{python}
#| eval: true
#| echo: false
#| message: false
#| warning: false

import pandas as pd
import numpy as np
import matplotlib
import plotnine as pn
from janitor import clean_names
from great_tables import GT as gt
import matplotlib.pyplot as plt
from pyhere import here
import arviz_base as azb
import arviz_plots as azp
import arviz_stats as azs
from pathlib import Path
import tempfile
from cmdstanpy import CmdStanModel
import joblib

pd.set_option('display.max_columns', None)
matplotlib.rcParams.update({'savefig.bbox': 'tight'})
```

# Loading in the Data from Shiny Application

```{python}
#| eval: true
#| echo: false

data = pd.read_csv(here('data_model_fit/df.csv')).drop(columns = 'Unnamed: 0')
q = pd.read_csv(here('data_model_fit/q.csv')).drop(columns = 'Unnamed: 0')
alpha = pd.read_csv(here('data_model_fit/alpha.csv')).drop(columns = 'Unnamed: 0')

diagnose = pd.read_csv(here('diagnostics/prior_diagnostics.csv'))
# prior_diagnose = pd.read_csv(here('diagnostics/prior_diagnostics.csv'))

main = joblib.load(here('data_model_fit/modfit.joblib'))
prior = joblib.load(here('data_model_fit/modfit_prior.joblib'))

fit = main[1]
pfit = prior[1]
```

Checklist of all the data that is loaded in.

-   Dataset of correct and incorrect answers for each question/item

-   User-defined Q-matrix

-   A table of each class (rows) and skills (columns)

    -   Classes are the groups students belong to based on the number of items/questions answered correctly

-   Diagnostic datasets similar to the diagnostic information on the shiny app. These values will indicate whether the model is accurately \_\_\_\_\_\_\_\_\_

-   Model Information

    -   This information will be used to get insight into how students answered items/questions and which students had the skills assessed in your quiz/assessment

```{python}
#| label: functions
#| eval: true
#| echo: false

def acceptable_fit_stat(idata):
  # only accepts loo right now
  est = np.abs(azs.loo(idata).elpd)
  se = azs.loo(idata).se
    
  if est > se * 2.5:
    print('Absolute difference is greater than 2.5 x the standard error of the difference. Model is acceptable.')
    
  else:
    print('Absolute difference is not greater than 2.5 x the standard error of the difference. Model is not acceptable.')


def q_lower(x):
    return x.quantile(.025)
  
def q_upper(x):
    return x.quantile(.975)
```

```{python}
#| eval: true
#| echo: false

stan_dict = {
  'J': data.shape[0],
  'I': data.shape[1],
  'C': alpha.shape[0],
  'K': q.shape[1] - 1,
  'Y': data.to_numpy(),
  'Q': q.iloc[:, 1:].to_numpy(),
  'alpha': alpha.to_numpy()
}

idata = azb.from_cmdstanpy(
    posterior = fit,
    prior = pfit,
    posterior_predictive = ['y_rep'],
    prior_predictive = ['y_rep'],
    observed_data = {'y_rep': stan_dict['Y']},
    log_likelihood = 'log_lik'
    )
```

```{python}
#| eval: true
#| echo: false

fitdf = fit.draws_pd()
```

# Diagnostics

The diagnostic information below can be used to see whether the model you created and ran is showing accurate values. **Note**: This does not mean this is a good mdoel, but simply that the model has worked correctly. Below are some guidelines that you can follow to see whether you might need to go back and try a new model.

-   **ESS_bulk** should be between NUMBER and NUMBER

-   **ESS_tail** should be between NUMBER and NUMBER

-   **R hat** values should be under 1.1

There are a few options that you can try out if your model did not work according to the guidelines above.

1.  Check the `Check this box if model does not converge` box, which will alter some of the model parameters to be more focused at new starting points for the model and have more detailed steps (this will take the models longer to run)

2.  Rethink the number of skills in your quiz

    -   Your model may not work if you have a low number of items/questions and a high number of skills

3.  Make sure the items/questions match the correct skill (this could be the issue)

    -   Double check that your Q-matrix is correctly identified

4.  Alter the priors, since your priors may be too restrictive and specific

```{python}
gt.show(gt(diagnose.sort_values('R_hat', ascending = False)[['ESS_bulk', 'ESS_tail', 'ESS_bulk/s', 'R_hat']].head()).tab_header(title = 'Diagnostics for Main Model'))
```

## Trace Plots

Trace plots are used as diagnostic plots. In these plots you should see what looks like static. If you see straight horizontal lines then that would be a sign that the model is wrong and should be rerun. If the plots are bad and the values above are either past the guidelines or close to those guideline values then you should rerun the model. Trace plots for all parameter values are included.

### Trace Plots for Slipping Parameter

```{python}
azp.plot_trace(idata, var_names = ['slip'])

# azp.plot_trace_dist(idata, var_names = ['slip'])
```

### Trace Plots for Guessing Parameter

```{python}
azp.plot_trace(idata, var_names = ['guess'])

# azp.plot_trace_dist(idata, var_names = ['guess'])
```

### Trace Plots for Nu Parameter (Class Proportions)

```{python}
azp.plot_trace(idata, var_names = ['nu'])

# azp.plot_trace_dist(idata, var_names = ['nu'])
```

### Trace Plots for Lambda Parameters (Probability of Proficiency in Each Skill)

```{python}
azp.plot_trace_dist(idata, var_names = ['lambda'], filter_vars = 'like')
```

### Trace Plots for Theta Parameters (Probability of Proficiency in Each Skill Based on Class Membeship)

```{python}
azp.plot_trace_dist(idata, var_names = ['theta'], filter_vars = 'like')
```

### Trace Plots for Pi Parameters (Probability of Getting Answer Correct for Each Class)

```{python}
azp.plot_trace_dist(idata, var_names = ['pi'], filter_vars = 'like')
```

# Prior vs Posterior Distributions

The plots below show where the prior distributions that you created from the shiny app for the parameters. These priors are then compared to the posterior distribution (the distribution of data that comes from the model once it has seen the data you uploaded).

Your priors and posteriors should have some overlap to show that your prior information matches the model once it has seen the data. If your priors and posteriors do not match, that means that your assumptions about your sample did not match the model findings once it has seen your data.

```{python}
azp.plot_prior_posterior( idata, var_names = ['slip'], kind = 'kde')
```

```{python}
azp.plot_prior_posterior( idata, var_names = ['guess'], kind = 'kde')
```

```{python}
azp.plot_prior_posterior(idata, var_names = ['lambda'], filter_vars = 'like', kind = 'kde')
```

# Posterior Predictive Model Checks (PPMC)

One thing that is helpful is to see how your model is compared to the actual data. The black line is the data that you uploaded. The blue lines are the distributions that are created when trying to replicate the actual data for comparison. You'll want the blue lines to surround the black line. If only some of the blue lines are surrounding the black line then that could be a visual indication that your model may not be replicating the data optimally. This does not necessarily mean you have an incorrect model.

If none of the blue lines are close to the black line then that is a clear indication that your model is incorrect and you may need to go back and rerun the model with different parameters.

```{python}
azp.plot_ppc_dist(idata, kind = 'kde', group = 'posterior_predictive')
```

Below is another option of viewing the data if this is clearer to understand.

```{python}
azp.plot_ppc_dist(idata, kind = 'ecdf', group = 'posterior_predictive',)
```

## Posterior Predictive P (PPP) value

PPP values are another method for assessing whether your model is accurately capturing the data you uploaded. These values are different from traditional p values because we are not interested in whether our sample is extremely different from the population. Instead, we want a ppp value to be around .5 to indicate that our posterior samples are similar to the actual data. 

Some guidelines are:

* Values closer to .5 are optimal

* Values on the edges (ppp < .1 or .05) indicate that the posterior samples are different from actual data, which is not what we want. We want our model to replicate the actual data well to have some more confidence in how our model behaves. 

For the purpose of ppp values, we could use a variety of statistics as metrics, but for simplicity I only included the mean and standard deviation and metrics. The ppp-value is not provided, but you can gauge it visually. If the dot is in the middle then that means your model is doing a good job of replicating your data. If it is on the edge, then your model may not be the most accurate. Be aware that this is the ppp-value for the overall model. There are also calculations at the item level to see if the replicated data is similar to the actual data for each item. This could also indicate what items are not getting captured well by the model.

**Note**: It is also important to note that if you have a small sample size (n < 50), this may just be a consequence of not having much data. There is also the possibility that some metrics, like the mean may look bad, but the standard deviation is good. This requires additional examination.

```{python}
azp.plot_ppc_tstat(idata, t_stat = 'mean')
```

```{python}
azp.plot_ppc_tstat(idata, t_stat = 'std')
```

## Item-Level PPP-values

Before we can conduct ppp-values for each item, I like to see the raw counts of the total scores for respondents in the actual data and how that compares to the average counts from our model. 

```{python}
#| eval: true
#| echo: false
#| warning: false
#| message: false
#| label: All code run for plots/tables


# slipping & guessing
sg = fitdf.filter(regex = 'guess|slip').reset_index()
sg = sg.rename(columns = {'index': 'draw'})

sglong = sg.melt(id_vars = 'draw')
sglong[['type', 'item']] = sglong['variable'].str.split('[', expand = True)
sglong['item'] = sglong['item'].str.replace(']', '')
sglong = sglong[['draw', 'type', 'item', 'value']]
sglong[['draw', 'item']] = sglong[['draw', 'item']].astype(int)

sgavg = sglong.groupby(['item', 'type'])

sgavg = pd.DataFrame({
  'mean': sgavg['value'].mean(),
  'std': sgavg['value'].std(),
  'q_lower': q_lower(sgavg['value']),
  'q_upper': q_upper(sgavg['value'])
}).reset_index()

# add actual labels to the latent classes
alpha['class_label'] = alpha.astype(int).astype(str).agg(''.join, axis = 1)
alpha = alpha.reset_index()
alpha['index'] = alpha['index'] + 1

# pi matrix (classes getting items correct)
pidf = fitdf.filter(regex = 'pi').reset_index()
pidf = pidf.rename(columns = {'index': 'draw'})
pilong = pidf.melt(id_vars = 'draw')
pilong['variable'] = pilong['variable'].str.replace('pi[', '')
pilong['variable'] = pilong['variable'].str.replace(']', '')
pilong[['item', 'latclass']] = pilong['variable'].str.split(',', expand = True)
pilong = pilong[['draw', 'item', 'latclass', 'value']]
pilong[['draw', 'item', 'latclass']] = pilong[['draw', 'item', 'latclass']].astype(int)

piavg = pilong.groupby(['item', 'latclass'])['value'].agg(['mean', 'std', q_lower, q_upper]).reset_index()

piavg = piavg.merge(alpha, 'left', left_on = 'latclass', right_on = 'index')

# replicated data
ydcm = fitdf.filter(regex = '^y_rep')

# calculations for odds ratios/conditional probabilities
ydcm_long = ydcm.melt()

ydcm_long['variable'] = ydcm_long['variable'].str.replace('y_rep[', '')
ydcm_long['variable'] = ydcm_long['variable'].str.replace(']', '')
ydcm_long[['stu', 'item']] = ydcm_long['variable'].str.split(',', expand = True)
ydcm_long = ydcm_long[['stu', 'item', 'value']]
ydcm_long[['stu', 'item']] = ydcm_long[['stu', 'item']].astype(int)
ydcm_long['draw'] = ydcm_long.groupby(['stu', 'item']).cumcount()

ydcm_wide = ydcm_long.pivot(index = ['stu', 'draw'], columns = 'item', values = 'value')
ydcm_wide = ydcm_wide.reset_index()

y_item_columns = [f'item{i}' for i in np.arange(stan_dict['I']) + 1]
ydcm_wide.columns = ['stu', 'draw'] + y_item_columns

ydcm_wide['total'] = ydcm_wide.filter(regex = 'item').sum(axis = 1)
ydcm_wide_count = ydcm_wide.groupby('draw')['total'].value_counts().reset_index()

ydcm_scores = ydcm_wide_count.groupby('total')['count'].agg(
    count = 'mean',
    lower = q_lower,
    upper = q_upper
).reset_index()

ydcm_wide_count['type'] = 'draw_counts'
ydcm_scores['type'] = 'avg_counts'

ydcm_wide_count['count'] = ydcm_wide_count['count'].astype(float)
ydcm_wide_count = ydcm_wide_count.merge(ydcm_scores, 'outer')

y_item = pd.DataFrame(stan_dict['Y'])
y_item.columns = y_item_columns

y_item['total'] = y_item.sum(axis = 1)
y_item_count = y_item['total'].value_counts().reset_index()
y_item_count['type'] = 'actual_counts'
y_item_count['count'] = y_item_count['count'].astype(float)

ydcm_wide_count = ydcm_wide_count.merge(y_item_count, 'outer')

# t-values
y_describe = y_item.filter(regex = 'item').agg(['mean', 'std']).reset_index()
y_describe.drop(columns = 'index').transpose().round(2)

stu_n = y_item.shape[0]

t_stats_dict = {}

# Loop from 1 to 7
for i in range(1, stan_dict['I']):
    item_name = f"item{i}"
    
    # Extract mean and std for the specific item
    # We use .values[0] to get the scalar number out of the filtered dataframe
    avg = y_describe.loc[y_describe['index'] == 'mean', item_name].values[0]
    std = y_describe.loc[y_describe['index'] == 'std', item_name].values[0]
    
    # Calculate the observed t-value
    # Formula: T = avg / (std / sqrt(n))
    t_val = avg / ((std + 1e-10) / np.sqrt(stu_n))
    
    # Store it in our dictionary
    t_stats_dict[item_name] = t_val

# Convert the dictionary into a final Pandas Series
obs_t_series = pd.Series(t_stats_dict)

obs_t_series = obs_t_series.reset_index()
obs_t_series = obs_t_series.rename(columns = {'index': 'item',
                                              0: 'observed_t'})
obs_t_series['item'] = obs_t_series['item'].str.replace('item', '')
obs_t_series['item'] = obs_t_series['item'].astype(float)

y_long_avg = ydcm_long.groupby(['item', 'draw'])['value'].agg(['mean', 'std']).reset_index()
y_long_avg['n'] = stu_n

y_long_avg['t_draw'] = y_long_avg['mean']/((y_long_avg['std'] + 1e-10)/np.sqrt(y_long_avg['n']))

y_long_avg = y_long_avg.merge(obs_t_series, 'inner', 'item')

# attribute calculations
attrdf = fitdf.filter(regex = '^prob_resp_attr').reset_index()
attrdf = attrdf.rename(columns = {'index': 'draw'})
attrlong = attrdf.melt(id_vars = 'draw')

attrlong['variable'] = attrlong['variable'].str.replace('prob_resp_attr[', '')
attrlong['variable'] = attrlong['variable'].str.replace(']', '')
attrlong[['stu', 'attr']] = attrlong['variable'].str.split(',', expand = True)
attrlong[['draw', 'stu', 'attr']] = attrlong[['draw', 'stu', 'attr']].astype(int)
attrlong = attrlong[['draw', 'stu', 'attr', 'value']]

attravg = attrlong.groupby(['stu', 'attr'])['value'].agg(['mean', 'std', q_lower, q_upper]).reset_index()

# mastery/proficiency thresholds
attravg['mastery'] = np.where(attravg['mean'] > threshold, 1, 0)

attr_w = attravg.pivot(index = 'stu', columns = 'attr', values = 'mastery').reset_index()

# reliability
attravg['acc_comp'] = attravg['mean'].apply(lambda p: max(p, 1 - p))
attravg['cons_comp'] = attravg['mean'].apply(lambda p: p**2 + (1 - p)**2)

# latent classes
attr_class = fitdf.filter(regex = '^prob_resp_class').reset_index()
attr_class = attr_class.rename(columns = {'index': 'draw'})
class_long = attr_class.melt(id_vars = 'draw')

class_long['variable'] = class_long['variable'].str.replace('prob_resp_class[', '')
class_long['variable'] = class_long['variable'].str.replace(']', '')
class_long[['stu', 'latclass']] = class_long['variable'].str.split(',', expand = True)
class_long[['draw', 'stu', 'latclass']] = class_long[['draw', 'stu', 'latclass']].astype(int)
class_long = class_long[['draw', 'stu', 'latclass', 'value']]

class_avg = class_long.groupby(['stu', 'latclass'])['value'].mean().reset_index()

class_stu_max = class_avg.groupby('stu')['value'].max().reset_index()

class_max = class_avg.merge(class_stu_max, 'inner')

class_max_df = class_max['latclass'].value_counts().reset_index()
class_max_df['latclass'] = class_max_df['latclass'].astype(object)
class_max_df = class_max_df.merge(alpha, 'left', left_on = 'latclass', right_on = 'index')
class_max_df = class_max_df[['class_label', 'count']]
```

The plot below shows how many respondents got the following totals in the actual data and the average counts from the posterior distributions with 95% credible intervals. The credible intervals show that we there is 95% confidence that the true value should be within the intervals. If the credible intervals have the actual value within them that is an indicator that the model captured the true value. 

```{python}
pn.ggplot.show(
  pn.ggplot(ydcm_wide_count.loc[ydcm_wide_count['type'] != 'draw_counts'],
            pn.aes('total',
                   'count'))
  + pn.geom_errorbar(pn.aes(ymin = 'lower',
                            ymax = 'upper'),
                     alpha = .5,
                     linetype = 'dashed')
  + pn.geom_point(pn.aes(color = 'type'), alpha = .8)
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.scale_x_continuous(limits = [1, piavg['item'].unique().max()],
                          breaks = piavg['item'].unique())
  + pn.labs(title = 'Comparisons between Actual Counts of Respondents\nGetting Items/Questions Correct',
  subtitle = 'And Posterior Average Correct')
  + pn.theme_light()
)
```

The following code calculates "t-values" to compare to the actual data to use a ppp-values for each item. Similar to the overall ppp-values before, we want the ppp-values for each item to be within .1 and .9. Anything outside of this range could indicate that the model did not capture the data accurately and may not be accurate.

```{python}
y_long_avg['t_draw'].describe()

t_compare_list = [np.mean(y_long_avg.loc[(y_long_avg['item'] == i), 't_draw'] > y_long_avg.loc[(y_long_avg['item'] == i), 'observed_t']) for i in np.arange(stan_dict['I'])]

gt.show(gt(pd.DataFrame({'item': np.arange(stan_dict['I']),
                         't_prop_over': t_compare_list}).round(2)).tab_header(title = 'Item Level PPMC'))

# pn.ggplot.show(
#   pn.ggplot(y_long_avg.loc[y_long_avg['item'] == 11],
#             pn.aes('t_draw'))
#   + pn.geom_density(color = 'black',
#                       fill = jpcolor,
#                       alpha = .5)
#   + pn.geom_vline(pn.aes(xintercept = 'observed_t'),
#                   color = 'red',
#                   linetype = 'dashed')
# )

# pd.DataFrame({'item': np.arange(stan_dict['I']),
#               't_prop_over': t_compare_list}).to_csv(here('diagnostics/item_level_ppmc.csv'))
```

# Classes

There was brief discussion on classes, but overall classes are respondents grouped into these groups based on what skill(s) they are proficient in. For 2 skills there will be four classes, which gives you the following options:

-   00 = Not proficient in either skill

-   10 = Proficient in skill 1, but not proficient in skill 2

-   01 = Not proficient in skill 1, but proficient in skill 2

-   11 = Proficient in both skills

```{python}
azp.plot_forest(idata, var_names = 'prob_resp_class')
```

We can also get the proportions of respondents that are in each class. This can indicate where the majority of students are at in regard to being proficient in the skills assessed in your quiz/assessment.

```{python}
# proportions

azp.plot_forest(idata, var_names = 'prob_attr_class')
```

# Proficiency/Mastery

Another 

Probability of skill mastery

```{python}
azp.plot_forest(idata, var_names = 'prob_resp_attr')
```

# Model Fit (WAIC & LOO)

**NEED TO WORK ON THIS SECTION**

```{python}
acceptable_fit_stat(idata)
```

# Item-Level Slipping & Guessing

**NEED TO WORK ON THIS SECTION**

```{python}
pn.ggplot.show(
  pn.ggplot(sgavg,
    pn.aes('factor(item)', 'mean'))
  + pn.geom_errorbar(pn.aes(ymin = 'q_lower', ymax = 'q_upper'),
  linetype = 'dashed',
  alpha = .7)
  + pn.geom_point(pn.aes(color = 'type'),
                  alpha = .7)
  + pn.coord_flip()
  + pn.facet_wrap('type')
  + pn.scale_y_continuous(limits = [0, 1],
                          breaks = np.arange(0, 1.1, .1))
  + pn.scale_color_brewer('qual', 'Dark2')
  + pn.labs(title = 'Probability of Guessing/Slipping',
            x = 'Item',
            y = 'Probability',
            caption = 'Guess = Guessed and got answer correct\nSlip = Should know the answer, but got the item wrong')
  + pn.theme_light()
  + pn.theme(legend_position = 'none')
)
```

# Probabilities of Each Class Getting Items Correct

**NEED TO WORK ON THIS SECTION**

```{python}
pn.ggplot.show(
  pn.ggplot(piavg,
            pn.aes('item',
                   'mean'))
  + pn.geom_errorbar(pn.aes(ymin = 'q_lower', ymax = 'q_upper'),
                     linetype = 'dashed',
                     color = 'gray',
                     alpha = .7)
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.geom_hline(yintercept = .5,
  color = 'black',
  linetype = 'dashed')
  + pn.scale_x_continuous(limits = [1, piavg['item'].unique().max()],
                          breaks = piavg['item'].unique())
  + pn.coord_flip()
  + pn.facet_wrap('class_label')
  + pn.labs(title = 'Probability of Getting Items Correct',
  subtitle = 'By Latent Class')
  + pn.theme_light()
  + pn.theme(legend_position = 'none')
)
```

# Skill Mastery

**NEED TO WORK ON THIS SECTION**

```{python}
pn.ggplot.show(
  pn.ggplot(attravg,
            pn.aes('stu',
                   'mean'))
  + pn.geom_errorbar(pn.aes(ymin = 'q_lower', ymax = 'q_upper'),
                     color = 'seagreen',
                     alpha = .1)
  + pn.geom_point(alpha = .7,
                  color = 'seagreen')
  + pn.geom_hline(yintercept = threshold,
                  color = 'black',
                  linetype = 'dashed')
  + pn.facet_wrap('attr')
  + pn.theme_light()
  + pn.theme(legend_position = 'none',
             axis_text_x = pn.element_blank())
)
```

**NEED TO WORK ON THIS SECTION**

```{python}
gt.show(gt(attr_w).tab_header(title = 'Proficiency in Skills'))
```

# Reliability

**NEED TO WORK ON THIS SECTION**

```{python}
reliability = attravg.groupby('attr').agg(
    accuracy=('acc_comp', 'mean'),
    consistency=('cons_comp', 'mean')
).reset_index()

gt.show(gt(reliability.round(3)).tab_header(title = 'Accuracy & Consistency'))
```

# Class Membership

**NEED TO WORK ON THIS SECTION**

```{python}
gt.show(gt(class_max_df).tab_header(title = 'Counts in Latent Classes'))
```
